name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  PROJECT: sub-web-modify

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码仓库
      uses: actions/checkout@v3  # 使用最新版本

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 登录 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 构建并推送 Docker 镜像
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT }}:latest          
